[package]
name = "day17"
version = "0.1.0"
authors = ["Eric Moss <eric@ericmoss.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
